### ISSUE TITLE
DiffusionNAG

### ISSUE THREAD

**Issue by sustech-lz** [CownowAn/DaSS#2]
Dear Hayeon Lee,

I hope this message finds you well. I recently came across your work titled "DiffusionNAG: Predictor-guided Neural Architecture Generation with Diffusion Models," and I was very impressed by the innovative approach and the promising results presented. The integration of diffusion models for neural architecture generation is particularly intriguing, and I believe it represents a significant advancement in the field.

I am keenly interested in exploring and understanding the methodologies and implementations detailed in your paper. I am currently attempting to replicate your work for further study and application within our projects.

However, I've encountered a challenge with opening and processing the datasets as described in your methodology. It seems there may be specific requirements or steps that I am missing, leading to difficulties in correctly accessing the data. This has impeded our progress and ability to fully appreciate the nuances of your work.

Given this, I was wondering if it might be possible for you to share the codebase or any related materials that could assist in resolving this issue. Additionally, any guidance or insights you could provide regarding the correct handling of the datasets would be immensely valuable. Your expertise and any further elaborations on the implementation details would greatly aid in our understanding and ability to replicate your impressive results.

Thank you very much for considering my request. Your work has sparked significant interest within our team, and we are eager to delve deeper into its potential applications. I look forward to the possibility of hearing back from you and perhaps even collaborating in some capacity in the future.

Warm regards,

**Comment by sustech-lz** [comment]
Specifically, the file downloaded from the OpenView website, ./checkpoints/scorenet/checkpoint.pth.tar and ./data/transfer_nag/nasbench201_info.pt, cannot be correctly opened. It seems there may be specific requirements or steps that I am missing, leading to difficulties in correctly accessing the data.

**Comment by HayeonLee** [comment]
Hi, thank you for your interest in our work. We will release the code, checkpoints, and dataset processing of DiffusionNAG in March. I will let you know if the code is released via this thread. Thank you.

**Comment by HayeonLee** [comment]
Hi @sustech-lz, we released the DiffusionNAG code: https://github.com/CownowAn/DiffusionNAG!
